export const POSTS = [
    {
        id: 1,
        username: "coolDude",
        profilePhoto: "https://source.unsplash.com/random/50x50",
        photo: "https://source.unsplash.com/random/1918x1080",
        title: "so awesome",
        description: "this is something cool",
    },
    {
        id: 2,
        username: "someDude",
        profilePhoto: "https://source.unsplash.com/random/50x51",
        photo: "https://source.unsplash.com/random/1918x1077",
        title: "wow",
        description: "this is cool",
    },
    {
        id: 3,
        username: "aDude",
        profilePhoto: "https://source.unsplash.com/random/50x52",
        photo: "https://source.unsplash.com/random/1919x1078",
        title: "Title",
        description: "this is something",
    },
    {
        id: 4,
        username: "randomDude",
        profilePhoto: "https://source.unsplash.com/random/50x53",
        photo: "https://source.unsplash.com/random/1919x1079",
        title: "something ",
        description: "this is ",
    },
    {
        id: 5,
        username: "weirdDude",
        profilePhoto: "https://source.unsplash.com/random/50x54",
        photo: "https://source.unsplash.com/random/1920x1080",
        title: "something weird",
        description: "this is something weird",
    },
    {
        id: 6,
        username: "1dude",
        profilePhoto: "https://source.unsplash.com/random/51x51",
        photo: "https://source.unsplash.com/random/1921x1080",
        title: "something Cool",
        description: "this is something cool",
    },
    {
        id: 7,
        username: "2dude",
        profilePhoto: "https://source.unsplash.com/random/51x50",
        photo: "https://source.unsplash.com/random/1922x1080",
        title: "something Cool",
        description: "this is something cool",
    },
    {
        id: 8,
        username: "3dude",
        profilePhoto: "https://source.unsplash.com/random/52x50",
        photo: "https://source.unsplash.com/random/1919x1080",
        title: "something Cool",
        description: "this is something cool",
    },
    {
        id: 9,
        username: "4dude",
        profilePhoto: "https://source.unsplash.com/random/53x50",
        photo: "https://source.unsplash.com/random/1918x1080",
        title: "something Cool",
        description: "this is something cool",
    },
    {
        id: 10,
        username: "5dude",
        profilePhoto: "https://source.unsplash.com/random/54x50",
        photo: "https://source.unsplash.com/random/1920x1081",
        title: "something Cool",
        description: "this is something cool",
    }
]